language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - android-24
    - build-tools-24.0.0
    - extra-android-m2repository

script: 
    - ./gradlew build

after_success: 
    - curl -F "file=app/build/outputs/apk/app-debug.apk" -F "uKey=${PGYER_APP_KEY}" -F "_api_key=${PGYER_API_KEY}" https://qiniu-storage.pgyer.com/apiv1/app/upload
