language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - android-25
    - build-tools-25.0.3
    - extra-android-m2repository

script: 
    - ./gradlew build

after_success: 
    - curl https://qiniu-storage.pgyer.com/apiv1/app/upload -F "uKey=${PGYER_APP_KEY}" -F "_api_key=${PGYER_API_KEY}" -F "file=@app/build/outputs/apk/app-debug.apk" &>/dev/null
