language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - android-25
    - build-tools-25.0.3
    - extra-android-m2repository

script: 
    - ./gradlew build

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
